### ISSUE TITLE
MDH doesn't work with any version of GZDoom, even the version older versions of GZDoom tell you to use.

### ISSUE THREAD

**Issue by BlendKitty** [OrdinaryVanity/mdo#9]
I've tried 4.6.0 and 4.11.3.a and they both give this error.

Script error, "mdhlevels.pk3:decorate/itemcrate/itemcrate.dec" line 1:
Parent type 'AbstractCrate' not found in ItemCrate
Script error, "mdhlevels.pk3:decorate/explosivebarrel/explosivebarrel.dec" line 1:
Parent type 'AbstractCrate' not found in MetroidExplosiveBarrel
Script error, "mdhlevels.pk3:decorate/enemies/prince.dec" line 1:
Parent type 'Boolean' not found in PrinceCloak
Script warning, "mdhlevels.pk3:zactors/keys.zsc" line 36:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhlevels.pk3:zactors/keys.zsc" line 80:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhlevels.pk3:zactors/keys.zsc" line 125:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zscript/grapplinghook/ghook.txt" line 25:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zscript/grapplinghook/ghook.txt" line 133:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zscript/grapplinghook/ghook.txt" line 142:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zactors/samusplayer.zc" line 146:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zactors/samusplayer.zc" line 151:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zactors/samusplayer.zc" line 314:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zactors/morphball.zc" line 85:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zactors/morphball.zc" line 90:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zactors/morphball.zc" line 253:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zactors/samusplayer.zc" line 522:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zactors/morphball.zc" line 373:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zactors/morphball.zc" line 381:
Accessing deprecated function A_PlaySoundEx - deprecated since 2.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zactors/morphball.zc" line 438:
Accessing deprecated function A_PlaySound - deprecated since 4.3.0, Use A_StartSound() instead
Script warning, "mdhmain.pk3:zactors/scanvisor.zc" line 73:
Accessing deprecated function A_PlaySoundEx - deprecated since 2.3.0, Use A_StartSound() instead
Script warning, "mdhlevels.pk3:decorate/enemies/prince.dec" line 79:
class 'PrinceCloak' is not compatible with 'Inventory'
Script warning, "mdhlevels.pk3:decorate/enemies/prince.dec" line 97:
class 'PrinceCloak' is not compatible with 'Inventory'
Script warning, "mdhlevels.pk3:decorate/enemies/prince.dec" line 109:
class 'PrinceCloak' is not compatible with 'Inventory'
Script warning, "mdhmain.pk3:decorate/gunship.dec" line 192:
Truncation of floating point constant 1.500000
Script warning, "mdhmain.pk3:decorate/gunship.dec" line 203:
Truncation of floating point constant 1.500000

Execution could not continue.

3 errors while parsing DECORATE scripts

Edit: I've tried the experimental branch on 4.8.2 and it gives a different error. I'm pretty sure they're related.

Script error, "Metroid - Demon Hunter Levels.pk3:decorate/itemcrate/itemcrate.dec" line 1:
Parent type 'AbstractCrate' not found in ItemCrate
Script error, "Metroid - Demon Hunter Levels.pk3:decorate/explosivebarrel/explosivebarrel.dec" line 1:
Parent type 'AbstractCrate' not found in MetroidExplosiveBarrel
Script error, "Metroid - Demon Hunter Levels.pk3:decorate/enemies/prince.dec" line 1:
Parent type 'Boolean' not found in PrinceCloak
Script warning, "Metroid - Demon Hunter Levels.pk3:decorate/enemies/prince.dec" line 79:
class 'PrinceCloak' is not compatible with 'Inventory'
Script warning, "Metroid - Demon Hunter Levels.pk3:decorate/enemies/prince.dec" line 97:
class 'PrinceCloak' is not compatible with 'Inventory'
Script warning, "Metroid - Demon Hunter Levels.pk3:decorate/enemies/prince.dec" line 109:
class 'PrinceCloak' is not compatible with 'Inventory'

**Comment by OrdinaryVanity** [comment]
This looks like you aren't loading all of the pk3 files/folders or you're loading them incorrectly.

You should be loading them in this order:
1. Main.pk3
2. MetroidLevels.pk3
3. Scans.pk3

How are you loading them? Dragging and dropping the files onto GZDoom.exe will most likely cause these to load in the incorrect order. I included a batch file that should load them correctly.

**Comment by BlendKitty** [comment]
> This looks like you aren't loading all of the pk3 files/folders or you're loading them incorrectly.
> 
> You should be loading them in this order:
> 
> 1. Main.pk3
> 2. MetroidLevels.pk3
> 3. Scans.pk3
> 
> How are you loading them? Dragging and dropping the files onto GZDoom.exe will most likely cause these to load in the incorrect order. I included a batch file that should load them correctly.

I used the bat file before but it gives out a error saying it cant find the game even if i put it in the GZDoom folder

**Comment by OrdinaryVanity** [comment]
> > This looks like you aren't loading all of the pk3 files/folders or you're loading them incorrectly.
> > You should be loading them in this order:
> > 
> > 1. Main.pk3
> > 2. MetroidLevels.pk3
> > 3. Scans.pk3
> > 
> > How are you loading them? Dragging and dropping the files onto GZDoom.exe will most likely cause these to load in the incorrect order. I included a batch file that should load them correctly.
> 
> I used the bat file before but it gives out a error saying it cant find the game even if i put it in the GZDoom folder

Can you send me a screenshot of what you have please? This works on the newest GZDoom without issue.

Also, it looks like you've renamed Metroid Levels to mdhlevels. If you plan to use the batch file you need to edit it to match.

**Comment by BlendKitty** [comment]
> > > This looks like you aren't loading all of the pk3 files/folders or you're loading them incorrectly.
> > > You should be loading them in this order:
> > > 
> > > 1. Main.pk3
> > > 2. MetroidLevels.pk3
> > > 3. Scans.pk3
> > > 
> > > How are you loading them? Dragging and dropping the files onto GZDoom.exe will most likely cause these to load in the incorrect order. I included a batch file that should load them correctly.
> > 
> > 
> > I used the bat file before but it gives out a error saying it cant find the game even if i put it in the GZDoom folder
> 
> Can you send me a screenshot of what you have please? This works on the newest GZDoom without issue.
> 
> Also, it looks like you've renamed Metroid Levels to mdhlevels. If you plan to use the batch file you need to edit it to match.

I only renamed the main branch files. After trying those I used the experimental with the default names. The error i got is
![image](https://github.com/OrdinaryVanity/mdh/assets/64370131/4d6a8454-e865-430c-a0e2-f044207f153b)
and this is the folder.
![image](https://github.com/OrdinaryVanity/mdh/assets/64370131/34dc21b5-bd47-4ac1-ad24-5ac16865511a)

**Comment by OrdinaryVanity** [comment]
You have to put the path to GZDoom in the batch file. I should update it to find it instead, but for now you should just need to replace "path to GZDoom" with the actual file path for GZDoom.

**Comment by BlendKitty** [comment]
I got it working, thanks!
